### ISSUE TITLE
[Bug] local location

### ISSUE THREAD

**Issue by trashpandagaming** [TrueSunnyD/Project-Prophecy#11]
1) [BUG]
2) there is a local that is clearly meant to be something but when i third eye them nothing pops up (location and evidence sent to you privatly)
3) Has this happened once? or multiple times? please specify: 2 times checked before and after a tsunami
4) Level of priority you feel is needed to take action and get this issue resolved 1 being the lowest 5 being the highest:3
5) Your discord name (please include #0000 numbers) example: Trash panda#2063

**Comment by TrueSunnyD** [comment]
Will be fixed on patch 1.35
