### ISSUE TITLE
[BUG] - Polywhirl Pokemon Card Disappears

### ISSUE THREAD

**Issue by BoboTheInsane** [TrueSunnyD/Project-Prophecy#12]
1) [BUG] or [EHNANCEMENT] please specify:  
Bug

2) Describe what's happening (please include as much detail as possible):
When pulling the Polywhirl card from packs, the card is not appearing in inventory.  You can see the card when turning over the cards after opening the pack, but the card is not given to the player.

3) Has this happened once? or multiple times? please specify:
Multiple times

4) Level of priority you feel is needed to take action and get this issue resolved 1 being the lowest 5 being the highest:
1  (if it's a gym badge card this might change)

5) Your discord name (please include #0000 numbers) example: TrueSunnyD#9925:
BoboTheInsane#7412

6) Please add pictures of any F8 errors (if any) when bug is happening or links if you have a video of it:
Did not see anything will check again next time it happens.

**Comment by TrueSunnyD** [comment]
Will be fixed on patch 1.35
