### ISSUE TITLE
[BUG] - Cascasde Badge Issues

### ISSUE THREAD

**Issue by BoboTheInsane** [TrueSunnyD/Project-Prophecy#13]
1) [BUG] or [ENHANCEMENT] please specify: 
Bug

2) Describe what's happening (please include as much detail as possible):
The Cascade badge is disappearing when placed inside of any storage other than your pockets.  It remains until you close the storage    and once you open it back up the badge is gone.  Once was apartment stash and other time was Pokebox that was in pockets.

When trading cards for the Cascade Badge the Golduck card is not being removed from the players pockets.

3) Has this happened once? or multiple times? please specify:
Multiple times on both issues

4) Level of priority you feel is needed to take action and get this issue resolved 1 being the lowest 5 being the highest:
1  (depending on if anything is locked behind League badge)

5) Your discord name (please include #0000 numbers) example: TrueSunnyD#9925:
BoboTheInsane#7412

6) Please add pictures of any F8 errors (if any) when bug is happening or links if you have a video of it:
No F8 errors

**Comment by TrueSunnyD** [comment]
Will be fixed on patch 1.35

**Comment by BoboTheInsane** [comment]
The fix for this:   
qb-core > shared > items.lua (line 1029)   {["name"] = "cascadeBadge",  to  {["name"] = "cascadebadge",
