### ISSUE TITLE
[BUG] - Earth Badge Not Attainable 

### ISSUE THREAD

**Issue by BoboTheInsane** [TrueSunnyD/Project-Prophecy#14]
1) [BUG] or [ENHANCEMENT] please specify: 
Bug

2) Describe what's happening (please include as much detail as possible):
When trying to trade the cards for the Earth Badge, it is saying that player does not have required items.  There are 2 cards listed as 6/6 for the Earth badge this may be the issue.  Cards in badge are 1/6 Rhydon, 2/6 Nidoking, 3/6 Nidoqueen, 5/6 Dugtrio, 6/6 Pidgeot, 6/6 Persian

3) Has this happened once? or multiple times? please specify:
Multiple

4) Level of priority you feel is needed to take action and get this issue resolved 1 being the lowest 5 being the highest:
1 (could change if anything is locked behind league badge)

5) Your discord name (please include #0000 numbers) example: TrueSunnyD#9925:
BoboTheInsane#7412

6) Please add pictures of any F8 errors (if any) when bug is happening or links if you have a video of it:
No errors appear, pictures of cards attached
![Earthbadge1](https://user-images.githubusercontent.com/112822668/188382017-de80e8a8-f5e9-4c14-a3da-d5873e97877a.PNG)
![Earthbadge2](https://user-images.githubusercontent.com/112822668/188382019-c128bfcf-9c16-4373-b168-46d79fba067f.PNG)

**Comment by TrueSunnyD** [comment]
Will be fixed on patch 1.35
