### ISSUE TITLE
Bugged oxy run

### ISSUE THREAD

**Issue by trashpandagaming** [TrueSunnyD/Project-Prophecy#24]
1. [BUG] or [EHNANCEMENT] please specify:
BUG
2. Describe what's happening (please include as much detail as possible): when trying a oxy run i never receive a drop off location no matter how long you wait
3. Has this happened once? or multiple times? please specify:
Multiple Times
4.Level of priority you feel is needed to take action and get this issue resolved 1 being the lowest 5 being the highest:
3
5.Your discord name (please include #0000 numbers) example: Trash panda#2063
6.Please add pictures of an F8 errors (if any) when bug is happening or links if you have a video of it:
![oxy error 2](https://user-images.githubusercontent.com/112376477/189540713-1720aac1-f99a-4a91-9596-95a2b9a53ac4.png)
![oxy run errors](https://user-images.githubusercontent.com/112376477/189540714-abec5643-a0bc-44cf-a471-cf82c709af96.png)

**Comment by TrueSunnyD** [comment]
Although i'm not sure why that error is popping up for something completely different... This script will be 100% fixed by server wipe as I have found the solution for it. Thank you for bringing this back to my attention again :)

**Comment by TrueSunnyD** [comment]
This will be fixed by next update. Thank you for reporting this :)
