### ISSUE TITLE
[BUG] - Item 'recvoucher' does not exist

### ISSUE THREAD

**Issue by BoboTheInsane** [TrueSunnyD/Project-Prophecy#26]
1) [BUG] or [EHNANCEMENT] please specify: 
Bug

2) Describe what's happening (please include as much detail as possible):
The item 'recvoucher' does not exist in qb-core > shared > items.lua   this item is rewarded for doing garbage job

3) Has this happened once? or multiple times? please specify:
multiple times

4) Level of priority you feel is needed to take action and get this issue resolved 1 being the lowest 5 being the highest:
3

5) Your discord name (please include #0000 numbers) example: TrueSunnyD#9925:
BoboTheInsane#7412

6) Please add pictures of any F8 errors (if any) when bug is happening or links if you have a video of it:
will test and comment if F8 error when awarded

**Comment by BoboTheInsane** [comment]
['recvoucher']  = {['name'] = 'recvoucher',    ['label'] = 'Recycling Voucher',   ['weight'] = 10,   ['type'] = 'item',     ['image'] =  'changeme.png',    ['unique'] = false,    ['useable'] = false,    ['shouldClose'] = false,    ['combinable'] = nil,    ['description'] = ""},

**Comment by TrueSunnyD** [comment]
Will be fixed by server wipe, thanks for the fix buddy
