### ISSUE TITLE
Sunrise

### ISSUE THREAD

**Issue by HarleenQ1** [TrueSunnyD/Project-Prophecy#27]
**[BUG] or [ENHANCEMENT] please specify:**

Enhancement

**Describe what's happening (please include as much detail as possible):**

If we are going back to the old car dealership script can we make it so people can test drive cars before we drive down to the docks to get them. 

Level of priority you feel is needed to take action and get this issue resolved 1 being the lowest 5 being the highest:
**5**

**Comment by TrueSunnyD** [comment]
Further going into this while it's fresh in my memory. 

Maybe think of a way to integrate the old dealership script into a unique location to allow test driving of vehicles, that way it doesn't interfere with the new vehicle script.

**Comment by TrueSunnyD** [comment]
Will not be bringing in the other dealership as there are still issues happening with it unfortunately
