### ISSUE TITLE
Black Jack is scuffed

### ISSUE THREAD

**Issue by sagexway** [TrueSunnyD/Project-Prophecy#29]
1) [BUG] or [EHNANCEMENT] please specify:  so when you play black jack... You dont gain more chips or lose chips in the game, 
2) Describe what's happening (please include as much detail as possible):I started a game with 40k chips and i played all night and never gained or lost any chips, almost like the game is in practice mode 
3) Has this happened once? or multiple times? please specify: so I was only used it on my two cousins, i used (sage elias) first and it happened then i switched to my cop cousin and the same thing happen
4) Level of priority you feel is needed to take action and get this issue resolved 1 being the lowest 5 being the highest: ehh... 3.3 tbh, its not really that important because it is just a side game in the city but I still gave it a 3.3 because I personally feel like BJ will help bring alot of entertainment in the city that we need
5) Your discord name (please include #0000 numbers) example: TrueSunnyD#9925: SageWay#1249
6) Please add pictures of any F8 errors (if any) when bug is happening or links if you have a video of it: none

**Comment by TrueSunnyD** [comment]
I will look into this and see if I can't get this all resolved by server wipe

**Comment by TrueSunnyD** [comment]
Black Jack has been removed and will be added back in the future
