### ISSUE TITLE
Lumber pricing 

### ISSUE THREAD

**Issue by trashpandagaming** [TrueSunnyD/Project-Prophecy#31]
1. [EHNANCEMENT]
2. Describe what's happening (please include as much detail as possible): debarked logs pricing is more then planks 
3. Has this happened once? or multiple times? please specify: N/A
4. Level of priority you feel is needed to take action and get this issue resolved 1 being the lowest 5 being the highest: 3
5. Your discord name (please include #0000 numbers) example: TrueSunnyD#9925: Trash panda#2063
6. Please add pictures of any F8 errors (if any) when bug is happening or links if you have a video of it:
![lumber prices](https://user-images.githubusercontent.com/112376477/191795651-61ceba79-d297-4faf-88d9-f73d40a28737.png)

**Comment by trashpandagaming** [comment]
I feel like planks should be more money since it's an extra process to make it

**Comment by TrueSunnyD** [comment]
This will be fixed on tonight's update
