### ISSUE TITLE
Can't hang up the phone 

### ISSUE THREAD

**Issue by trashpandagaming** [TrueSunnyD/Project-Prophecy#32]
1. [BUG] or [EHNANCEMENT] please specify: bug
2. Describe what's happening (please include as much detail as possible): when talking on the phone you can't hang up it says can't hang-up while talking to someone
3. Has this happened once? or multiple times? please specify: 3 people have had the same issue 
4. Level of priority you feel is needed to take action and get this issue resolved 1 being the lowest 5 being the highest: 5
5. Your discord name (please include #0000 numbers) example: Trash panda#2063
6. Please add pictures of any F8 errors (if any) when forgot to look

**Comment by TrueSunnyD** [comment]
/endcall or press the up arrow key in order to hang up with the new phone update
