### ISSUE TITLE
[BUG] - Cannot add people to locks on house

### ISSUE THREAD

**Issue by BoboTheInsane** [TrueSunnyD/Project-Prophecy#34]
1) [BUG] or [EHNANCEMENT] please specify: 
Bug

2) Describe what's happening (please include as much detail as possible):
When adding people to Nickyxpop gang for locks on MLO they are not able to lock and unlock doors

3) Has this happened once? or multiple times? please specify:
multiple

4) Level of priority you feel is needed to take action and get this issue resolved 1 being the lowest 5 being the highest:
2

5) Your discord name (please include #0000 numbers) example: TrueSunnyD#9925:
BoboTheInsane#7412

6) Please add pictures of any F8 errors (if any) when bug is happening or links if you have a video of it:
None

**Comment by Kirkalirk98** [comment]
Not really a bug,
How it's currently set up is only Nickyxpop can go in the house because of her CitizenID # since the new door lock came in.
This will be change so she can give people house keys
