### ISSUE TITLE
[BUG] - Pistol ammo is turning into shotgun after purchased

### ISSUE THREAD

**Issue by BoboTheInsane** [TrueSunnyD/Project-Prophecy#35]
1) [BUG] or [EHNANCEMENT] please specify: 
bug

2) Describe what's happening (please include as much detail as possible):
Purchase pistol ammo from the weapon store on Spanish Ave. and Power St., after leaving shop menu and going back into inventory the pistol ammo turns to shotgun ammo

3) Has this happened once? or multiple times? please specify:
multiple

4) Level of priority you feel is needed to take action and get this issue resolved 1 being the lowest 5 being the highest:
4
5) Your discord name (please include #0000 numbers) example: TrueSunnyD#9925:
BoboTheInsane#7412

6) Please add pictures of any F8 errors (if any) when bug is happening or links if you have a video of it:
No F8 errors

**Comment by BoboTheInsane** [comment]
Possibly a slot number issue, there is a dead slot in weapon shop now
--Was a slot number issue fix in dm,  can close

**Comment by TrueSunnyD** [comment]
Fixed and applied for Patch 1.37 Hot Fixes
