### ISSUE TITLE
[BUG] - Fishing Shop Dead Slot (Fix)

### ISSUE THREAD

**Issue by BoboTheInsane** [TrueSunnyD/Project-Prophecy#36]
1) [BUG] or [EHNANCEMENT] please specify: 
Bug

2) Describe what's happening (please include as much detail as possible):
Fishfinder is not appearing in fishing shop, item is mislabeled in [qb]\qb-shops\config.lua  line 1357  is name = "fishfinder",   needs to be name = "fish-finder", to match items.lua

3) Has this happened once? or multiple times? please specify:
multiple

4) Level of priority you feel is needed to take action and get this issue resolved 1 being the lowest 5 being the highest:
3

5) Your discord name (please include #0000 numbers) example: TrueSunnyD#9925:
BoboTheInsane#7412

6) Please add pictures of any F8 errors (if any) when bug is happening or links if you have a video of it:
Fix above in description no F8

**Comment by TrueSunnyD** [comment]
Fixed and applied for Patch 1.37 Hot Fixes
