### ISSUE TITLE
[FIX] - Cascade Badge Disappearing

### ISSUE THREAD

**Issue by BoboTheInsane** [TrueSunnyD/Project-Prophecy#37]
Fixed cascade badge disappearing when putting in inventory   qb-core > shared > items.lua (line 1029) {["name"] = "cascadeBadge",  to 
	{["name"] = "cascadebadge",

Discord: BoboTheInsane#7412

**Comment by TrueSunnyD** [comment]
Will be applied on Patch 1.43 update
