### ISSUE TITLE
[BUG] - Old Oxy Run Local

### ISSUE THREAD

**Issue by BoboTheInsane** [TrueSunnyD/Project-Prophecy#38]
1) [BUG] or [ENHANCEMENT] please specify: 
Bug

2) Describe what's happening (please include as much detail as possible):
The old oxy run local is still in city, can third eye but does not allow you to do anything and doesn't take or give anything.
possible still has code in qb-target:main.lua  (line 596)

3) Has this happened once? or multiple times? please specify:
multiple times

4) Level of priority you feel is needed to take action and get this issue resolved 1 being the lowest 5 being the highest:
3
5) Your discord name (please include #0000 numbers) example: TrueSunnyD#9925:
BoboTheInsane#7412

6) Please add pictures of any F8 errors (if any) when bug is happening or links if you have a video of it:
pictures in dm

**Comment by TrueSunnyD** [comment]
Will be applied on Patch 1.43
