### ISSUE TITLE
[FIX] - Pokemon Eart Badge Card Descriptions

### ISSUE THREAD

**Issue by BoboTheInsane** [TrueSunnyD/Project-Prophecy#39]
If desired to match Earth Badge Gym in the Show, remove pidgeot from earth badge and add mewtwo  (My Bad)
Below is description fixes based on which 

	-Yes add mewtwo-
-Change description of pidgeot to ""   qb-core > shared > items.lua (line 1177)
-Change Earth Badge to require mewtwo instead of pidgeot  qb-pokemontcg > config.lua (line 118)

	-No keep pidgeot-
-Change description of pidgeot to "4/6 for Earth Badge"   qb-core > shared > items.lua  (line 1177)
-Change description of mewtwo to "Ultra Rare"   qb-core > shared > items.lua (line 1103)

Discord: BoboTheInsane#7412

**Comment by TrueSunnyD** [comment]
This will be fixed on Patch 1.38 with Mewtwo addition
