### ISSUE TITLE
Recycling Center giving lower bulk returns

### ISSUE THREAD

**Issue by Mizkana** [TrueSunnyD/Project-Prophecy#41]
1) [BUG] or [EHNANCEMENT] please specify: Bug
2) Describe what's happening (please include as much detail as possible):
Recycling gives less items for bigger bulk trades (1 trade gives 1 item but 1000 gave me around 200 materials total)
3) Has this happened once? or multiple times? please specify: Multiple
4) Level of priority you feel is needed to take action and get this issue resolved 1 being the lowest 5 being the highest:3
5) Your discord name (please include #0000 numbers): Mizkana#3244
6) Please add pictures of any F8 errors (if any) when bug is happening or links if you have a video of it:

**Comment by TrueSunnyD** [comment]
This will be balanced for Patch 1.38
