### ISSUE TITLE
[BUG] - Trucking Cargo is taking longer than usual

### ISSUE THREAD

**Issue by BoboTheInsane** [TrueSunnyD/Project-Prophecy#42]
1) [BUG] or [ENHANCEMENT] please specify: 
Bug

2) Describe what's happening (please include as much detail as possible):
When selecting job, you have to double click the Start Job button, then a pop up appears saying "" and after about 15+ seconds another pop up appears saying "Your cargo is taking longer than usual to load. Try again"  tried multiple jobs with different distances and cargo types.

3) Has this happened once? or multiple times? please specify:
multiple and multiple people

4) Level of priority you feel is needed to take action and get this issue resolved 1 being the lowest 5 being the highest:
5

5) Your discord name (please include #0000 numbers) example: TrueSunnyD#9925:
BoboTheInsane#7412

6) Please add pictures of any F8 errors (if any) when bug is happening or links if you have a video of it:
No F8 errors, pictures attached also in scuffs folder
![cargo](https://user-images.githubusercontent.com/112822668/192363603-1ea83c54-9a30-4520-b221-6da58d61a32e.PNG)
![cargofail](https://user-images.githubusercontent.com/112822668/192363611-758352ae-a200-41bb-957b-cd13f9a3b50a.PNG)

**Comment by TrueSunnyD** [comment]
This will be fixed by Patch 1.38
