### ISSUE TITLE
[BUG] -  r14-evidnce errors

### ISSUE THREAD

**Issue by BoboTheInsane** [TrueSunnyD/Project-Prophecy#44]
1) [BUG] or [ENHANCEMENT] please specify: 
Bug

2) Describe what's happening (please include as much detail as possible):
not sure what trigger them, woke up at Sunrise got panto out of garage, unlocked and locked door and drove.

3) Has this happened once? or multiple times? please specify:
multiple times in F8 

4) Level of priority you feel is needed to take action and get this issue resolved 1 being the lowest 5 being the highest:
2

5) Your discord name (please include #0000 numbers) example: TrueSunnyD#9925:
BoboTheInsane#7412

6) Please add pictures of any F8 errors (if any) when bug is happening or links if you have a video of it:
Pictures Attached, also in Scuffs folder in PM
![r14-evidence error](https://user-images.githubusercontent.com/112822668/192358569-b8dea4bf-73ad-47e3-a840-5bff0849afd3.PNG)
![r14-evidence error2](https://user-images.githubusercontent.com/112822668/192358571-3bf57f33-5ae1-49ec-932d-a5418744a5a5.PNG)
![r14-evidence error3](https://user-images.githubusercontent.com/112822668/192360528-2e24b4eb-28ca-4112-a807-217ccb865d8a.PNG)

**Comment by TrueSunnyD** [comment]
This should be fixed on Patch 1.38 I will be monitoring this and re-opening this ticket if these errors still persist
