### ISSUE TITLE
[BUG] - Butcher Local Missing

### ISSUE THREAD

**Issue by BoboTheInsane** [TrueSunnyD/Project-Prophecy#45]
1) [BUG] or [ENHANCEMENT] please specify: 
Bug

2) Describe what's happening (please include as much detail as possible):
The local is not in the spot he is supposed to be  (unless was moved recently)
possibly the model is being used by another shop, or missing location data code in hunting script

3) Has this happened once? or multiple times? please specify:
multiple

4) Level of priority you feel is needed to take action and get this issue resolved 1 being the lowest 5 being the highest:
4

5) Your discord name (please include #0000 numbers) example: TrueSunnyD#9925:
BoboTheInsane#7412

6) Please add pictures of any F8 errors (if any) when bug is happening or links if you have a video of it:
no F8 errors, pictures sent in PM  scuffs folder

**Comment by TrueSunnyD** [comment]
The local was moved from a prior patch :)
