### ISSUE TITLE
Car rental ped

### ISSUE THREAD

**Issue by HarleenQ1** [TrueSunnyD/Project-Prophecy#46]
[BUG] or [ENHANCEMENT] please specify:
BUG
   
 Describe what's happening (please include as much detail as possible):
 The Ped you rent cars from if you find him other places he'll let you rent a car but it spawns where the original rental car spawns   
   
Level of priority you feel is needed to take action and get this issue resolved 1 being the lowest 5 being the highest:
2
   
 Your discord name (please include #0000 numbers) example::
Nickyxpop#7237

**Comment by BoboTheInsane** [comment]
Need to switch ped model from a_m_y_business_03 in qb-rentals:client:main.lua as well as qb-target data, to a scenario style ped model.

**Comment by TrueSunnyD** [comment]
Will be fixed on Patch 1.38
