### ISSUE TITLE
[Bug] Item missing with scrapping cars

### ISSUE THREAD

**Issue by trashpandagaming** [TrueSunnyD/Project-Prophecy#48]
1. [BUG] or [ENHANCEMENT] please specify:
Bug
2. Describe what's happening (please include as much detail as possible): when scrapping cars got an error for an item not existing
3. Has this happened once? or multiple times? please specify: 1 time so far will do more testing
4. Level of priority you feel is needed to take action and get this issue resolved 1 being the lowest 5 being the highest: 3
5. Your discord name (please include #0000 numbers) example: TrueSunnyD#9925: Trash panda#2063
6. Please add pictures of any F8 errors (if any) when bug is happening or links if you have a video of it:
![missing item scrapping](https://user-images.githubusercontent.com/112376477/195963659-54666073-d18f-4b24-9463-a0a393f7dd81.png)

**Comment by BoboTheInsane** [comment]
Missing item is a window, code is missing from [qb]\qb-core\shared\items.lua  add near Line 1009   code to fix below:

['chop-window'] 			     = {['name'] = 'chop-window', 			     	['label'] = 'Window', 		    	    ['weight'] = 500, 		['type'] = 'item', 		['image'] = 'changeme.png', 					['unique'] = false, 		['useable'] = true, 	['shouldClose'] = true,    ['combinable'] = nil,   ['description'] = 'Chopped up windshield'},

**Comment by BoboTheInsane** [comment]
Code for [qb]\qb-scrapyard\client\main.lua  add between lines 185 and 438

{
            header = "Exchange Window",
            txt = "Exchange an Window for materials",
            params = {
                event = "qb-scrapyard:client:exchangeItems",
                args = {
                    itemremove = "chop-window",
                    item = "glass",
                    amountremove = 1,
                    amount = math.random(5,10)
                },
                isServer = false
            }
        },

**Comment by TrueSunnyD** [comment]
Thanks bobo!!! This will be fixed by patch 1.40
