### ISSUE TITLE
[EHNANCEMENT] SNOW!

### ISSUE THREAD

**Issue by Dew-Frost1** [TrueSunnyD/Project-Prophecy#51]
[BUG] or [EHNANCEMENT] please specify: [EHNANCEMENT]
2) Describe what's happening (please include as much detail as possible): The weather is normal. I would like snow sometimes/all the time for the season. 
3) Has this happened once? or multiple times? please specify: I have never seen any snow. 
4) Level of priority you feel is needed to take action and get this issue resolved 1 being the lowest 5 being the highest:  1, lowest. If this can be done easily then I think it would be great. If it is difficult it should be ignored. 
5) Your discord name (please include #0000 numbers) example: TrueSunnyD#9925: Skyman#6995
6) Please add pictures of any F8 errors (if any) when bug is happening or links if you have a video of it: No bug. Any type of snow would be cool, either just snow fall or snow on the road or both.

**Comment by TrueSunnyD** [comment]
Applied on last update
