### ISSUE TITLE
[BUG] - Sound Issue

### ISSUE THREAD

**Issue by ChodySkanck** [TrueSunnyD/Project-Prophecy#52]
1) [BUG] or [EHNANCEMENT] please specify: 
*BUG*   
**The 2022 Lamborghini Huracan EVO 2 does not produce any sound at all in city, it is dead quiet while driving or turning on or anything.**

2) Describe what's happening (please include as much detail as possible): **The car makes you deaf basically when you drive it unless you pass other vehicles.**

3) Has this happened once? or multiple times? please specify: **This happens every time you pull it out and use it, it is completely broken.**

4) Level of priority you feel is needed to take action and get this issue resolved 1 being the lowest 5 being the highest:  **1**

5) Your discord name (please include #0000 numbers) example: TrueSunnyD#9925:    Skanck#6613

6) Please add pictures of any F8 errors (if any) when bug is happening or links if you have a video of it: **If you fly in and spawn the car you will see what I'm talking about.**

**Comment by TrueSunnyD** [comment]
This will be applied and fixed on next update (Patch 1.43)
