### ISSUE TITLE
Black Market

### ISSUE THREAD

**Issue by HarleenQ1** [TrueSunnyD/Project-Prophecy#9]
1) [BUG]
2) Describe what's happening: 
Black Market (location sent to you privately) Is appearing as the original black market.
3) Has this happened once? or multiple times? please specify: 
Yes
4) Level of priority you feel is needed to take action and get this issue resolved 1 being the lowest 5 being the highest:
5
5) Your discord name: 
nickyxpop#7237

**Comment by TrueSunnyD** [comment]
Will be fixed on patch 1.35
